version: '3.8'

services:
  frontend:
    image: inventory-frontend:latest
    restart: unless-stopped
    ports:
      - 3000:80
    networks:
      - ansible-inventory-network
    depends_on:
      - backend

  backend:
    image: inventory-backend:latest
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - ansible-inventory-network
    volumes:
      - ./backend/.env:/app/.env:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ansible-inventory-network:
    driver: bridge
